language: php

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - composer self-update && composer install --dev
    - vendor/tedivm/dovecottesting/SetupEnvironment.sh


script: ./tests/runTests.sh

after_script:
    - php vendor/bin/coveralls -v